### ISSUE TITLE
end of file reached (EOFError)

### ISSUE THREAD

**Issue by olea** [fedora-ruby/gem2rpm#37]
Just installed in Fedora:

``` bash
$ rpm -q rubygem-gem2rpm
rubygem-gem2rpm-0.10.1-1.fc20.noarch
```
But I can't make it work in any way:

``` bash
$ gem2rpm 
/usr/share/gems/gems/gem2rpm-0.10.1/lib/gem2rpm/distro.rb:19:in `readline': end of file reached (EOFError)
	from /usr/share/gems/gems/gem2rpm-0.10.1/lib/gem2rpm/distro.rb:19:in `block in nature'
	from /usr/share/gems/gems/gem2rpm-0.10.1/lib/gem2rpm/distro.rb:18:in `each'
	from /usr/share/gems/gems/gem2rpm-0.10.1/lib/gem2rpm/distro.rb:18:in `nature'
	from /usr/share/gems/gems/gem2rpm-0.10.1/lib/gem2rpm.rb:77:in `<module:Gem2Rpm>'
	from /usr/share/gems/gems/gem2rpm-0.10.1/lib/gem2rpm.rb:9:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/gems/gems/gem2rpm-0.10.1/bin/gem2rpm:6:in `<top (required)>'
	from /usr/bin/gem2rpm:23:in `load'
	from /usr/bin/gem2rpm:23:in `<main>'
``` 

I'm not into ruby so I don't know how to diagnose it,  if it's a Fedora packaging bug or what.

**Comment by voxik** [comment]
Could you please provide output of ```$ ls -la /etc/*{_version,-release}*```. Mine is something like:

```
$ ls -la /etc/*{_version,-release}*
ls: cannot access /etc/*_version*: No such file or directory
-rw-r--r--. 1 root root  31 Nov 22 01:52 /etc/fedora-release
-rw-r--r--. 1 root root 377 Nov 22 01:52 /etc/os-release
lrwxrwxrwx. 1 root root  14 Nov 22 01:52 /etc/redhat-release -> fedora-release
lrwxrwxrwx. 1 root root  14 Nov 22 01:52 /etc/system-release -> fedora-release
-rw-r--r--. 1 root root  31 Nov 22 01:52 /etc/system-release-cpe
```

I'd say that some of there files on your system is empty, which is a bit unexpected.

**Comment by olea** [comment]
``` console

$ ls -la /etc/*{_version,-release}*
ls: cannot access /etc/*_version*: No such file or directory
-rw-r--r--  1 root root   30 feb 19  2014 /etc/fedora-release
-rw-r--r--  1 root root    0 jun 12  2014 /etc/lsb-release~
-rw-r--r--  1 root root  375 feb 19  2014 /etc/os-release
lrwxrwxrwx  1 root root   14 abr  9  2014 /etc/redhat-release -> fedora-release
lrwxrwxrwx  1 root root   14 abr  9  2014 /etc/system-release -> fedora-release
-rw-r--r--  1 root root   31 feb 19  2014 /etc/system-release-cpe

/etc/lsb-release.d:
total 16
drwxr-xr-x.   2 root root  4096 sep 21 15:11 .
drwxr-xr-x. 210 root root 12288 mar  3 10:42 ..
-rw-r--r--    1 root root     0 sep  1  2014 core-4.1-amd64
-rw-r--r--    1 root root     0 sep  1  2014 core-4.1-noarch
-rw-r--r--    1 root root     0 sep  1  2014 cxx-4.1-amd64
-rw-r--r--    1 root root     0 sep  1  2014 cxx-4.1-noarch
-rw-r--r--    1 root root     0 sep  1  2014 desktop-4.1-amd64
-rw-r--r--    1 root root     0 sep  1  2014 desktop-4.1-noarch
-rw-r--r--    1 root root     0 sep  1  2014 languages-4.1-amd64
-rw-r--r--    1 root root     0 sep  1  2014 languages-4.1-noarch
-rw-r--r--    1 root root     0 sep  1  2014 printing-4.1-amd64
-rw-r--r--    1 root root     0 sep  1  2014 printing-4.1-noarch

```

Hum, I see this /etc/lsb-release~ file to be empty. Removing it now I get:

``` console
$ gem2rpm 
Missing GEMFILE
Usage: /usr/bin/gem2rpm [OPTIONS] GEM
  Convert ruby Gems to source RPMs and specfiles
  Uses a template to generate the RPM specfile
  from the Gem spec

  Options:
    -T, --current-template           Print the current template
    -t, --template TEMPLATE          Use TEMPLATE for the specfile
    -v, --version                    Print gem2rpm's version and exit
    -o, --output FILE                Send the specfile to FILE
    -s, --srpm                       Create a source RPM
    -l, --local                      Do not retrieve Gem information over
                                     the network. Use on disconnected machines
    -d, --dependencies               Print the dependencies of the gem
    -n, --nongem                     Generate a subpackage for non-gem use
        --no-doc                     Disable document subpackage
        --fetch                      Fetch the gem from rubygems.org

  Arguments:
    GEM            the path to locally stored gem package file or the name
                   of the gem when using --fetch.

``` 

Thanks!
