### ISSUE TITLE
Throw OpenURI::HTTPError with --fetch no_existed_gem_name.

### ISSUE THREAD

**Issue by junaruga** [fedora-ruby/gem2rpm#66]
Throw the error with --fetch.
I think that we can handle the error, and print the user friendly error message.

```
$ bin/gem2rpm --version
0.11.3

$ bin/gem2rpm --fetch gem2rpm-foo
/usr/local/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 404 Not Found (OpenURI::HTTPError)
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:717:in `open'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:35:in `open'
    from bin/gem2rpm:36:in `<main>'
```

It is similar with below issue.
https://github.com/fedora-ruby/gem2rpm/issues/55

**Comment by salmanQbatch** [comment]
I am facing this issue while starting server can any one help me ???

**Comment by pvalena** [comment]
> I am facing this issue while starting server can any one help me ???

This should be already solved. Please check with the newest gem2rpm version and file a new Issue in case it does not work for you.
