### ISSUE TITLE
--templates does not work

### ISSUE THREAD

**Issue by junaruga** [fedora-ruby/gem2rpm#67]
```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

$ bin/gem2rpm --version
0.11.3

$ bin/gem2rpm --templates
Available templates in #{Gem2Rpm::Template.default_location}:\n\n
#<Enumerator:0x0056321c8a2218>
/home/jaruga/git/gem2rpm_jaruga/lib/gem2rpm/configuration.rb:159:in `block in setup_parser_options': undefined method `join' for nil:NilClass (NoMethodError)
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/optparse.rb:1540:in `block in parse_in_order'  
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/optparse.rb:1527:in `catch'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/optparse.rb:1527:in `parse_in_order'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/optparse.rb:1521:in `order!'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/optparse.rb:1613:in `permute!'
    from /usr/local/ruby-2.3.0/lib/ruby/2.3.0/optparse.rb:1635:in `parse!'
    from /home/jaruga/git/gem2rpm_jaruga/lib/gem2rpm/configuration.rb:114:in `handle_options'
    from /home/jaruga/git/gem2rpm_jaruga/lib/gem2rpm/configuration.rb:105:in `options'
    from bin/gem2rpm:12:in `<main>'
```

**Comment by voxik** [comment]
I fixed this ... but the test coverage would be nice anyway ...
