### ISSUE TITLE
`gem2rpm --fetch` fails in directory without permissions

### ISSUE THREAD

**Issue by voxik** [fedora-ruby/gem2rpm#92]
```
$ pwd
/

$ gem2rpm --fetch gem2rpm
/usr/share/ruby/open-uri.rb:37:in `initialize': Permission denied @ rb_sysopen - /gem2rpm-1.0.0.gem (Errno::EACCES)
	from /usr/share/ruby/open-uri.rb:37:in `open'
	from /usr/share/ruby/open-uri.rb:37:in `open'
	from /usr/share/gems/gems/gem2rpm-1.0.0/bin/gem2rpm:59:in `block in <top (required)>'
	from /usr/share/ruby/open-uri.rb:155:in `open_uri'
	from /usr/share/ruby/open-uri.rb:721:in `open'
	from /usr/share/ruby/open-uri.rb:35:in `open'
	from /usr/share/gems/gems/gem2rpm-1.0.0/bin/gem2rpm:55:in `<top (required)>'
	from /usr/bin/gem2rpm:22:in `load'
	from /usr/bin/gem2rpm:22:in `<main>'
```

**Comment by clime** [comment]
Just hit the same issue.
